### ISSUE TITLE
Warning messages during Circ.test()

### ISSUE THREAD

**Issue by jorgeboucas** [dieterich-lab/CircTest#2]
The following warning messages when trying Circ.test() with the processed Westholm et al. data from CircTest package appears 10x.

```
Warning messages:
1: In betabin(cbind(circ, tot - circ) ~ group, ~1, data = testdat) : 
Possible convergence problem. Optimization process code: 10 (see ?optim).
```

**Comment by FranziMe** [comment]
Sadly it is not possible to catch this warning during the for-loop, thus I cannot add a column to the output table indicating for which circles the warning is given.
