### ISSUE TITLE
Error in -del_row : invalid argument to unary operator

### ISSUE THREAD

**Issue by idotu** [dieterich-lab/CircTest#6]
When I run Circ.filter with the output from DCC in R I get this error. When I run it from circtools it doesn't appear. Any help would be much appreciated.

ivan

**Comment by idotu** [comment]
It only happens when percentage flag is too low (like 0.00001)

**Comment by tjakobi** [comment]
Dear @idotu,

please update your CircTest installation; the latest commit should fix your error.

Cheers,
Tobias

**Comment by tjakobi** [comment]
Additional information: `circtools` uses a more sophisticated wrapper script that already does some pre-filtering and therefore probably does not reach this unhandled part of code.
