### ISSUE TITLE
Add circRNA/total count ratio

### ISSUE THREAD

**Issue by CDieterich** [dieterich-lab/CircTest#8]
Dear Tobias,

please add circular over total count ration to spreadsheet output.

**Comment by tjakobi** [comment]
The `circ.test()` function now generates additional columns at the end of the `summary_table` containing the mean of all replicates per group. The ratios are additionally returned in the `ratios` object of `circ.test()`.

**Comment by tjakobi** [comment]
Note: when CircTest is updated this functionality automatically becomes available in `circtools`.
