### ISSUE TITLE
Question: FDR-corrected P value from circTest

### ISSUE THREAD

**Issue by knuppd** [dieterich-lab/CircTest#9]
Hi dieterich lab,

I was wondering if the p-value given by circTest output in R is adjusted or unadjusted? If unadjusted, is there a way to get the adjusted p?

Thank you,

Dave

**Comment by tjakobi** [comment]
Hi @knuppd,

the p-value provided by circTest is BH-adjusted:

```
p.adj <- p.adjust(p.val,n=sum(!is.na(p.val)),'BH')
```

Cheers,
Tobias
